"""empty message

Revision ID: 03ddf527ef04
Revises: d340c7812c63
Create Date: 2024-01-25 17:48:47.998900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ddf527ef04'
down_revision = 'd340c7812c63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__contest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('F_Voting', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__contest', schema=None) as batch_op:
        batch_op.drop_column('F_Voting')

    # ### end Alembic commands ###
