"""empty message

Revision ID: 03f7a89a0cfe
Revises: 6792ec5aafda
Create Date: 2023-11-22 22:02:00.853229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03f7a89a0cfe'
down_revision = '6792ec5aafda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('F_ChatImage', sa.String(length=256), nullable=True))
        batch_op.alter_column('F_ChatContest',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__chat', schema=None) as batch_op:
        batch_op.alter_column('F_ChatContest',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('F_ChatImage')

    # ### end Alembic commands ###
