"""empty message

Revision ID: 3d6035ae762b
Revises: 1d143e62db9a
Create Date: 2023-12-20 21:57:54.361957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6035ae762b'
down_revision = '1d143e62db9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t__contest_master',
    sa.Column('F_ContestMasterID', sa.Integer(), nullable=False),
    sa.Column('F_ContestMasterTitle', sa.String(length=256), nullable=False),
    sa.Column('F_ContestMasterImage', sa.LargeBinary(), nullable=False),
    sa.Column('F_ContestMasterContent', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('F_ContestMasterID'),
    sa.UniqueConstraint('F_ContestMasterTitle')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t__contest_master')
    # ### end Alembic commands ###
