"""empty message

Revision ID: 4808df78e9d8
Revises: 615360d531b9
Create Date: 2023-11-05 21:58:49.705654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4808df78e9d8'
down_revision = '615360d531b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__exhibit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('F_ExPhotoS', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('F_ExPhotoT', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('F_ExPhotoF', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('F_ExPhotoH', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__exhibit', schema=None) as batch_op:
        batch_op.drop_column('F_ExPhotoH')
        batch_op.drop_column('F_ExPhotoF')
        batch_op.drop_column('F_ExPhotoT')
        batch_op.drop_column('F_ExPhotoS')

    # ### end Alembic commands ###
