"""empty message

Revision ID: 4a5c36b82201
Revises: 922030940bf1
Create Date: 2024-02-06 13:37:51.725058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5c36b82201'
down_revision = '922030940bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__foster_pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('F_FosterPeriod', sa.Boolean(), nullable=True))

    with op.batch_alter_table('t__lost_pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('F_FosterPeriod', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__lost_pet', schema=None) as batch_op:
        batch_op.drop_column('F_FosterPeriod')

    with op.batch_alter_table('t__foster_pet', schema=None) as batch_op:
        batch_op.drop_column('F_FosterPeriod')

    # ### end Alembic commands ###
