"""empty message

Revision ID: 4c8cc8b7e03e
Revises: 7dd99393058f
Create Date: 2023-12-09 17:30:49.654695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c8cc8b7e03e'
down_revision = '7dd99393058f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['F_Email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
