"""empty message

Revision ID: 53738ae22f55
Revises: 
Create Date: 2023-10-21 23:04:32.043888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53738ae22f55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t__user',
    sa.Column('F_UserID', sa.Integer(), nullable=False),
    sa.Column('F_UserName', sa.String(length=80), nullable=False),
    sa.Column('F_Password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('F_UserID'),
    sa.UniqueConstraint('F_UserName')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t__user')
    # ### end Alembic commands ###
