"""empty message

Revision ID: 61488e070bf1
Revises: 61814db59bd6
Create Date: 2024-02-07 22:10:58.994189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61488e070bf1'
down_revision = '61814db59bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__contest_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('F_CouponID', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 't__coupon', ['F_CouponID'], ['F_CouponID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__contest_master', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('F_CouponID')

    # ### end Alembic commands ###
