"""empty message

Revision ID: 615360d531b9
Revises: c6690fa1be56
Create Date: 2023-11-05 21:55:02.565081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615360d531b9'
down_revision = 'c6690fa1be56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__exhibit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('F_EXhibitType', sa.Integer(), nullable=False))

    with op.batch_alter_table('t__user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('F_Profile_Comment', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__user', schema=None) as batch_op:
        batch_op.drop_column('F_Profile_Comment')

    with op.batch_alter_table('t__exhibit', schema=None) as batch_op:
        batch_op.drop_column('F_EXhibitType')

    # ### end Alembic commands ###
