"""empty message

Revision ID: 61814db59bd6
Revises: 4a5c36b82201
Create Date: 2024-02-07 09:41:19.048025

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61814db59bd6'
down_revision = '4a5c36b82201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t__message',
    sa.Column('F_MessageID', sa.Integer(), nullable=False),
    sa.Column('F_UserID', sa.Integer(), nullable=False),
    sa.Column('F_Message', sa.String(length=256), nullable=False),
    sa.Column('F_TimeStamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['F_UserID'], ['t__user.F_UserID'], ),
    sa.PrimaryKeyConstraint('F_MessageID')
    )
    with op.batch_alter_table('t__exhibit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('F_Width', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('F_Height', sa.Integer(), nullable=False))

    with op.batch_alter_table('t__pet', schema=None) as batch_op:
        batch_op.alter_column('F_Size',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__pet', schema=None) as batch_op:
        batch_op.alter_column('F_Size',
               existing_type=sa.String(length=256),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('t__exhibit', schema=None) as batch_op:
        batch_op.drop_column('F_Height')
        batch_op.drop_column('F_Width')

    op.drop_table('t__message')
    # ### end Alembic commands ###
