"""empty message

Revision ID: 61e281bb954e
Revises: de60ebb680bd
Create Date: 2023-11-02 23:11:11.774621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61e281bb954e'
down_revision = 'de60ebb680bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__user', schema=None) as batch_op:
        batch_op.alter_column('F_BirthDay',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__user', schema=None) as batch_op:
        batch_op.alter_column('F_BirthDay',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
