"""empty message

Revision ID: 7714600bcbeb
Revises: cf53247ab9d7
Create Date: 2023-11-14 14:04:26.977528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7714600bcbeb'
down_revision = 'cf53247ab9d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t__point',
    sa.Column('F_PointID', sa.Integer(), nullable=False),
    sa.Column('F_PointQuantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('F_PointID')
    )
    op.create_table('T_Login',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['point_id'], ['t__point.F_PointID'], ),
    sa.ForeignKeyConstraint(['user_id'], ['t__user.F_UserID'], ),
    sa.PrimaryKeyConstraint('user_id', 'point_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('T_Login')
    op.drop_table('t__point')
    # ### end Alembic commands ###
