"""empty message

Revision ID: 7abd95ffdda7
Revises: d92f213781b4
Create Date: 2023-11-14 21:27:42.937392

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7abd95ffdda7'
down_revision = 'd92f213781b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t__login',
    sa.Column('F_LoginID', sa.Integer(), nullable=False),
    sa.Column('F_PointID', sa.Integer(), nullable=False),
    sa.Column('F_UserID', sa.Integer(), nullable=False),
    sa.Column('F_LoginTime', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['F_PointID'], ['t__point.F_PointID'], ),
    sa.ForeignKeyConstraint(['F_UserID'], ['t__user.F_UserID'], ),
    sa.PrimaryKeyConstraint('F_LoginID')
    )
    with op.batch_alter_table('t__user', schema=None) as batch_op:
        batch_op.drop_column('points')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', mysql.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('t__login')
    # ### end Alembic commands ###
