"""empty message

Revision ID: 7dd99393058f
Revises: c92e2688f107
Create Date: 2023-11-27 14:46:24.697439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd99393058f'
down_revision = 'c92e2688f107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t__contest',
    sa.Column('F_ContestID', sa.Integer(), nullable=False),
    sa.Column('F_ContestTitle', sa.String(length=256), nullable=False),
    sa.Column('F_ContestImage', sa.String(length=256), nullable=False),
    sa.Column('F_ContestComment', sa.String(length=256), nullable=False),
    sa.Column('F_UserID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['F_UserID'], ['t__user.F_UserID'], ),
    sa.PrimaryKeyConstraint('F_ContestID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t__contest')
    # ### end Alembic commands ###
