"""empty message

Revision ID: 922030940bf1
Revises: 03ddf527ef04
Create Date: 2024-01-25 18:30:29.240950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922030940bf1'
down_revision = '03ddf527ef04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t__coupon',
    sa.Column('F_CouponID', sa.Integer(), nullable=False),
    sa.Column('F_CouponCode', sa.String(length=256), nullable=False),
    sa.Column('F_CouponDis', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('F_CouponID'),
    sa.UniqueConstraint('F_CouponCode')
    )
    op.create_table('t__coupon_pos',
    sa.Column('F_CouponPosID', sa.Integer(), nullable=False),
    sa.Column('F_UserID', sa.Integer(), nullable=False),
    sa.Column('F_CouponID', sa.Integer(), nullable=False),
    sa.Column('F_CouponQuantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['F_CouponID'], ['t__coupon.F_CouponID'], ),
    sa.ForeignKeyConstraint(['F_UserID'], ['t__user.F_UserID'], ),
    sa.PrimaryKeyConstraint('F_CouponPosID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t__coupon_pos')
    op.drop_table('t__coupon')
    # ### end Alembic commands ###
