"""empty message

Revision ID: 94956765bbc1
Revises: 3d6035ae762b
Create Date: 2023-12-20 22:06:35.377298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94956765bbc1'
down_revision = '3d6035ae762b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__contest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('F_ContestMasterID', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 't__contest_master', ['F_ContestMasterID'], ['F_ContestMasterID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__contest', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('F_ContestMasterID')

    # ### end Alembic commands ###
