"""empty message

Revision ID: 99387601f368
Revises: 4808df78e9d8
Create Date: 2023-11-08 14:25:48.161450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99387601f368'
down_revision = '4808df78e9d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__exhibit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('F_ExTag', sa.String(length=256), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__exhibit', schema=None) as batch_op:
        batch_op.drop_column('F_ExTag')

    # ### end Alembic commands ###
