"""empty message

Revision ID: 998080452f39
Revises: 7abd95ffdda7
Create Date: 2023-11-14 21:31:51.007501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '998080452f39'
down_revision = '7abd95ffdda7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t__login')
    with op.batch_alter_table('t__point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('F_UserID', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 't__user', ['F_UserID'], ['F_UserID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__point', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('F_UserID')

    op.create_table('t__login',
    sa.Column('F_LoginID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('F_PointID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('F_UserID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('F_LoginTime', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['F_PointID'], ['t__point.F_PointID'], name='t__login_ibfk_1'),
    sa.ForeignKeyConstraint(['F_UserID'], ['t__user.F_UserID'], name='t__login_ibfk_2'),
    sa.PrimaryKeyConstraint('F_LoginID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
