"""empty message

Revision ID: 9af9a7e2a0a1
Revises: 94956765bbc1
Create Date: 2023-12-31 22:01:02.761161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af9a7e2a0a1'
down_revision = '94956765bbc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__contest_master', schema=None) as batch_op:
        batch_op.alter_column('F_ContestMasterImage',
               existing_type=sa.BLOB(),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__contest_master', schema=None) as batch_op:
        batch_op.alter_column('F_ContestMasterImage',
               existing_type=sa.String(length=256),
               type_=sa.BLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
