"""empty message

Revision ID: 9fd06de8aa77
Revises: 7ebdfc4e1cf0
Create Date: 2023-11-22 17:28:34.148888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd06de8aa77'
down_revision = '7ebdfc4e1cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__lost_pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('F_PetID', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 't__pet', ['F_PetID'], ['F_PetID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__lost_pet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('F_PetID')

    # ### end Alembic commands ###
