"""empty message

Revision ID: a1bf076c6d46
Revises: 99387601f368
Create Date: 2023-11-09 18:01:47.298804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1bf076c6d46'
down_revision = '99387601f368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t__category',
    sa.Column('F_CategoryID', sa.Integer(), nullable=False),
    sa.Column('F_CategoryName', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('F_CategoryID'),
    sa.UniqueConstraint('F_CategoryName')
    )
    with op.batch_alter_table('t__exhibit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('F_ExSit', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('F_ExDeli', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('F_CategoryID', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 't__category', ['F_CategoryID'], ['F_CategoryID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__exhibit', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('F_CategoryID')
        batch_op.drop_column('F_ExDeli')
        batch_op.drop_column('F_ExSit')

    op.drop_table('t__category')
    # ### end Alembic commands ###
