"""empty message

Revision ID: c6690fa1be56
Revises: 61e281bb954e
Create Date: 2023-11-03 20:46:12.162953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6690fa1be56'
down_revision = '61e281bb954e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t__paramerter',
    sa.Column('F_ID', sa.Integer(), nullable=False),
    sa.Column('F_userid', sa.Integer(), nullable=False),
    sa.Column('F_friendid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['F_friendid'], ['t__user.F_UserID'], ),
    sa.ForeignKeyConstraint(['F_userid'], ['t__user.F_UserID'], ),
    sa.PrimaryKeyConstraint('F_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t__paramerter')
    # ### end Alembic commands ###
