"""empty message

Revision ID: cf53247ab9d7
Revises: f25ba1af9039
Create Date: 2023-11-13 21:37:24.960536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf53247ab9d7'
down_revision = 'f25ba1af9039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t__favorite',
    sa.Column('F_FavoriteID', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exhibit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exhibit_id'], ['t__exhibit.F_ExID'], ),
    sa.ForeignKeyConstraint(['user_id'], ['t__user.F_UserID'], ),
    sa.PrimaryKeyConstraint('F_FavoriteID')
    )
    op.drop_table('f__favorite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('f__favorite',
    sa.Column('F_FavoriteID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exhibit_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exhibit_id'], ['t__exhibit.F_ExID'], name='f__favorite_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['t__user.F_UserID'], name='f__favorite_ibfk_2'),
    sa.PrimaryKeyConstraint('F_FavoriteID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('t__favorite')
    # ### end Alembic commands ###
