"""empty message

Revision ID: d340c7812c63
Revises: bad5b6b6da13
Create Date: 2024-01-23 14:19:15.711399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd340c7812c63'
down_revision = 'bad5b6b6da13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__contest_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('F_ContestPeriod', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('F_VotingPeriod', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__contest_master', schema=None) as batch_op:
        batch_op.drop_column('F_VotingPeriod')
        batch_op.drop_column('F_ContestPeriod')

    # ### end Alembic commands ###
