"""empty message

Revision ID: d509a6dd875a
Revises: 53738ae22f55
Create Date: 2023-10-24 14:07:05.750484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd509a6dd875a'
down_revision = '53738ae22f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('F_SignUpDay', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('F_BirthDay', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('F_Gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('F_Telphone', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('F_Email', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('F_Residence', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('F_PosttalCode', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('F_LastName', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('F_FirstName', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('F_LastName_Kana', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('F_FirstName_Kana', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('F_ProfileImage', sa.String(length=256), nullable=False))
        batch_op.alter_column('F_UserName',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('F_Password',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__user', schema=None) as batch_op:
        batch_op.alter_column('F_Password',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('F_UserName',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('F_ProfileImage')
        batch_op.drop_column('F_FirstName_Kana')
        batch_op.drop_column('F_LastName_Kana')
        batch_op.drop_column('F_FirstName')
        batch_op.drop_column('F_LastName')
        batch_op.drop_column('F_PosttalCode')
        batch_op.drop_column('F_Residence')
        batch_op.drop_column('F_Email')
        batch_op.drop_column('F_Telphone')
        batch_op.drop_column('F_Gender')
        batch_op.drop_column('F_BirthDay')
        batch_op.drop_column('F_SignUpDay')

    # ### end Alembic commands ###
