"""empty message

Revision ID: d50f0a30f1bb
Revises: 9fd06de8aa77
Create Date: 2023-11-22 21:26:47.979633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd50f0a30f1bb'
down_revision = '9fd06de8aa77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__pet', schema=None) as batch_op:
        batch_op.alter_column('F_Castration',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__pet', schema=None) as batch_op:
        batch_op.alter_column('F_Castration',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)

    # ### end Alembic commands ###
