"""empty message

Revision ID: f25ba1af9039
Revises: 4e82135d4d4f
Create Date: 2023-11-13 21:33:12.368923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f25ba1af9039'
down_revision = '4e82135d4d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('f__favorite',
    sa.Column('F_FavoriteID', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exhibit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exhibit_id'], ['t__exhibit.F_ExID'], ),
    sa.ForeignKeyConstraint(['user_id'], ['t__user.F_UserID'], ),
    sa.PrimaryKeyConstraint('F_FavoriteID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('f__favorite')
    # ### end Alembic commands ###
