"""empty message

Revision ID: fc0d609dddab
Revises: 9af9a7e2a0a1
Create Date: 2024-01-03 21:32:28.109224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc0d609dddab'
down_revision = '9af9a7e2a0a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__contest_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('F_ContestMasterTime', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__contest_master', schema=None) as batch_op:
        batch_op.drop_column('F_ContestMasterTime')

    # ### end Alembic commands ###
